openapi: "3.0.2"
info:
    title: API Title
    version: "1.0"
servers:
    - url: https://localhost:1001/authentication/api/v1
paths:
    /auth/sign-up:
        post:
            tags:
                - authentication
            summary: Add new user
            description: create new user by using email, password and password
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    example: "example@example.com"
                                password:
                                    type: string
                                    example: PhamDucLuu20215084@
            responses:
                "200":
                    description: OK
                "400":
                    description: Invalid parameters
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
